"""
Core data models for the novelist project.

Pydantic models for type-safe data handling across the system.
All SSOT (Single Source of Truth) data structures are defined here.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any, Literal
from pydantic import BaseModel, Field


class CharacterCard(BaseModel):
    """
    Character definition for consistent portrayal.
    
    Maps to: characters/*.json
    Reference: docs/keikaku.md Section 5.1 - Character Cards
    """
    id: str = Field(..., description="Unique character identifier")
    name: Dict[str, str] = Field(..., description="Full, short, and alias names")
    basic: Dict[str, Any] = Field(default_factory=dict, description="Age, gender, race, etc.")
    language: Dict[str, Any] = Field(..., description="Speech patterns and constraints")
    personality: Dict[str, Any] = Field(default_factory=dict, description="Values, motivations, fears")
    relationships: Dict[str, Dict[str, str]] = Field(default_factory=dict, description="Relations with other characters")
    background: Dict[str, Any] = Field(default_factory=dict, description="Origin and key events")
    narrative: Dict[str, Any] = Field(default_factory=dict, description="Role in story, secrets, plot hooks")
    
    def format_for_prompt(self) -> str:
        """Format character card for inclusion in prompts."""
        lines = [
            f"## {self.name.get('full', 'Unknown')}",
            f"- **一人称**: {self.language.get('first_person', '私')}",
            f"- **口調**: {self.language.get('tone', '')}",
            f"- **話し方**: {self.language.get('speech_pattern', '')}",
            f"- **価値観**: {', '.join(self.personality.get('values', []))}",
        ]
        
        if self.language.get('forbidden_words'):
            lines.append(f"- **禁則語**: {', '.join(self.language['forbidden_words'])}")
        
        if self.relationships:
            lines.append("- **関係性**:")
            for char_id, relation in self.relationships.items():
                lines.append(f"  - {relation.get('name', char_id)}: {relation.get('relation', '')}")
        
        return '\n'.join(lines)


class Fact(BaseModel):
    """
    Immutable fact extracted from the narrative.
    
    Maps to: memory/facts.json
    Reference: docs/keikaku.md Section 5.1 - Facts
    """
    id: str = Field(..., description="Fact identifier (f001, f002, ...)")
    content: str = Field(..., description="Fact statement")
    category: Literal["immutable", "variable"] = Field(default="immutable")
    source: str = Field(..., description="Chapter/scene where fact was established")
    created_at: Optional[str] = None
    tags: List[str] = Field(default_factory=list)


class Foreshadowing(BaseModel):
    """
    Foreshadowing tracking for plot consistency.
    
    Maps to: memory/foreshadow.json
    Reference: docs/keikaku.md Section 5.1 - Foreshadowing
    """
    id: str = Field(..., description="Foreshadowing identifier (fs001, ...)")
    content: str = Field(..., description="Description of the foreshadowing")
    status: Literal["unresolved", "resolved", "abandoned"] = Field(default="unresolved")
    created_in: str = Field(..., description="Chapter where foreshadowing was planted")
    target_resolution: Optional[str] = None
    related_chapters: List[str] = Field(default_factory=list)
    resolution_chapter: Optional[str] = None
    resolution_note: Optional[str] = None
    priority: Literal["high", "medium", "low"] = Field(default="medium")
    tags: List[str] = Field(default_factory=list)


class SceneSpec(BaseModel):
    """
    Scene specification generated by Director.
    
    Reference: docs/keikaku.md Section 5.1 - SceneSpec
    """
    scene: Dict[str, Any] = Field(..., description="ID, chapter, sequence, title")
    narrative: Dict[str, Any] = Field(..., description="Objective, events, revelations, hooks")
    constraints: Dict[str, Any] = Field(..., description="POV, location, characters, mood")
    continuity: Dict[str, Any] = Field(default_factory=dict, description="Facts, foreshadowing to resolve/plant")
    style: Dict[str, Any] = Field(default_factory=dict, description="Pacing, dialogue ratio, techniques")
    output: Dict[str, Any] = Field(default_factory=dict, description="Target length, ending type")


class Bible(BaseModel):
    """
    World and style bible for consistent narrative.
    
    Maps to: bible.md
    Reference: docs/keikaku.md Section 5.1 - Style/World Bible
    """
    style_rules: Dict[str, Any] = Field(default_factory=dict, description="Style Bible section")
    world_settings: Dict[str, Any] = Field(default_factory=dict, description="World Bible section")
    raw_content: str = Field(default="", description="Raw markdown content")
    
    def format_style_section(self) -> str:
        """Format Style Bible for prompts."""
        lines = ["## Style Bible（文体規約）"]
        
        if "viewpoint" in self.style_rules:
            lines.append(f"- **視点**: {self.style_rules['viewpoint']}")
        if "first_person" in self.style_rules:
            lines.append(f"- **一人称**: {self.style_rules['first_person']}")
        if "sentence_ending" in self.style_rules:
            lines.append(f"- **文末**: {self.style_rules['sentence_ending']}")
        if "metaphors" in self.style_rules:
            lines.append(f"- **比喩**: {self.style_rules['metaphors']}")
        if "forbidden" in self.style_rules:
            lines.append(f"- **禁則**: {', '.join(self.style_rules['forbidden'])}")
        
        return '\n'.join(lines)
    
    def format_world_section(self) -> str:
        """Format World Bible for prompts."""
        lines = ["## World Bible（世界観）"]
        
        if "overview" in self.world_settings:
            lines.append(f"- **概要**: {self.world_settings['overview']}")
        if "magic_system" in self.world_settings:
            lines.append(f"- **魔法体系**: {self.world_settings['magic_system']}")
        if "technology" in self.world_settings:
            lines.append(f"- **技術水準**: {self.world_settings['technology']}")
        
        return '\n'.join(lines)


class EpisodicMemory(BaseModel):
    """
    Recent scene summaries for context.
    
    Maps to: memory/episodic.md
    Reference: docs/keikaku.md Section 5.1 - Episodic Recap
    """
    current_arc: str = Field(default="", description="Current story arc name")
    arc_summary: str = Field(default="", description="Summary of current arc")
    recent_scenes: List[Dict[str, Any]] = Field(default_factory=list, description="Last N scenes")
    character_status: Dict[str, Dict[str, str]] = Field(default_factory=dict, description="Current character locations/conditions")
    active_threads: List[Dict[str, Any]] = Field(default_factory=list, description="Ongoing plot threads")
    unresolved_tensions: List[str] = Field(default_factory=list, description="Current tensions")


class ProjectConfig(BaseModel):
    """
    Project configuration.
    
    Maps to: config.yaml
    Reference: docs/keikaku.md Section 10
    """
    version: str = "1.0"
    project_name: str = "My Novel"
    
    provider: Dict[str, Any] = Field(default_factory=dict)
    context: Dict[str, Any] = Field(default_factory=dict)
    swarm: Dict[str, Any] = Field(default_factory=dict)
    generation: Dict[str, Any] = Field(default_factory=dict)
    output: Dict[str, Any] = Field(default_factory=dict)
    logging: Dict[str, Any] = Field(default_factory=dict)
    quality: Dict[str, Any] = Field(default_factory=dict)
    security: Dict[str, Any] = Field(default_factory=dict)


class GenerationResult(BaseModel):
    """Result of text generation."""
    text: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    model: str = ""
    provider: str = ""
    duration_ms: int = 0
    timestamp: datetime = Field(default_factory=datetime.now)


class RunLog(BaseModel):
    """Single execution log entry."""
    run_id: str
    timestamp: datetime
    agent: str
    operation: str
    prompt: Optional[str] = None
    output: Optional[str] = None
    metrics: Dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None
