#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
STAMP="$(date +%Y%m%d-%H%M%S)"
TAG="$STAMP"
PKG_NAME=""
OUT_DIR=""

WITH_IMAGES=1

checksum_program() {
  if command -v sha256sum >/dev/null 2>&1; then
    echo "sha256sum"
    return 0
  fi
  if command -v shasum >/dev/null 2>&1; then
    echo "shasum -a 256"
    return 0
  fi
  return 1
}

hash_file() {
  local path="$1"
  local rel_path="$2"

  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | awk -v rel="$rel_path" '{print $1 "  " rel}'
    return 0
  fi

  shasum -a 256 "$path" | awk -v rel="$rel_path" '{print $1 "  " rel}'
}

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

  --with-images          Build and include Docker images in images.tar (default)
  --no-images            Package files only (smaller archive)
  --output <dir>         Output directory (default: ./dist)
  --tag <name>           Package tag suffix (default: timestamp)
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --with-images)
      WITH_IMAGES=1
      ;;
    --no-images)
      WITH_IMAGES=0
      ;;
    --output)
      if [ "$#" -lt 2 ]; then
        echo "Missing value for --output"
        exit 1
      fi
      DIST_DIR="$2"
      shift
      ;;
    --tag)
      if [ "$#" -lt 2 ]; then
        echo "Missing value for --tag"
        exit 1
      fi
      TAG="$2"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
  shift
done

if [[ ! "$TAG" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo "--tag must match [A-Za-z0-9._-]+"
  exit 1
fi

if [ "${DIST_DIR#/}" = "$DIST_DIR" ]; then
  DIST_DIR="$ROOT_DIR/$DIST_DIR"
fi

PKG_NAME="novelist-local-${TAG}"
OUT_DIR="$DIST_DIR/$PKG_NAME"

if ! checksum_program >/dev/null 2>&1; then
  echo "sha256sum or shasum command is required."
  exit 1
fi

mkdir -p "$DIST_DIR"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

cp -R "$ROOT_DIR/deploy/local/." "$OUT_DIR/"

# Exclude runtime state (models, keys, generated project files) from distributable bundle.
rm -rf "$OUT_DIR/data"
mkdir -p "$OUT_DIR/data"
cat > "$OUT_DIR/data/.gitignore" <<'EOF'
# Runtime state generated by ./start.sh
*
!.gitignore
EOF

cat > "$OUT_DIR/VERSION" <<EOF
package_name: ${PKG_NAME}
generated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
with_images: ${WITH_IMAGES}
EOF

if [ "$WITH_IMAGES" -eq 1 ]; then
  if ! command -v docker >/dev/null 2>&1; then
    echo "docker command is required for --with-images."
    exit 1
  fi

  echo "Building novelist-local image..."
  docker build -t novelist-local:latest "$ROOT_DIR"

  echo "Pulling runtime images..."
  docker pull ollama/ollama:latest
  docker pull nginx:alpine

  echo "Exporting images to images.tar..."
  docker save \
    novelist-local:latest \
    ollama/ollama:latest \
    nginx:alpine \
    -o "$OUT_DIR/images.tar"
fi

pushd "$OUT_DIR" >/dev/null
{
  hash_file "$OUT_DIR/README.md" "README.md"
  hash_file "$OUT_DIR/VERSION" "VERSION"
  hash_file "$OUT_DIR/docker-compose.yml" "docker-compose.yml"
  hash_file "$OUT_DIR/start.sh" "start.sh"
  hash_file "$OUT_DIR/stop.sh" "stop.sh"
  hash_file "$OUT_DIR/status.sh" "status.sh"
  hash_file "$OUT_DIR/load-images.sh" "load-images.sh"
  hash_file "$OUT_DIR/data/.gitignore" "data/.gitignore"
  if [ -f "$OUT_DIR/images.tar" ]; then
    hash_file "$OUT_DIR/images.tar" "images.tar"
  fi
} > "$OUT_DIR/SHA256SUMS"
popd >/dev/null

ARCHIVE_PATH="$DIST_DIR/${PKG_NAME}.tar.gz"
tar -czf "$ARCHIVE_PATH" -C "$DIST_DIR" "$PKG_NAME"
hash_file "$ARCHIVE_PATH" "$(basename "$ARCHIVE_PATH")" > "$ARCHIVE_PATH.sha256"

echo "Local distribution package created:"
echo "  directory: $OUT_DIR"
echo "  archive:   $ARCHIVE_PATH"
echo "  checksum:  $OUT_DIR/SHA256SUMS"
echo "  archive sha256: $ARCHIVE_PATH.sha256"
