#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
STAMP="$(date +%Y%m%d-%H%M%S)"
PKG_NAME="novelist-local-${STAMP}"
OUT_DIR="$DIST_DIR/$PKG_NAME"

WITH_IMAGES=1

usage() {
  cat <<EOF
Usage: $(basename "$0") [--with-images|--no-images]

  --with-images  Build and include Docker images in images.tar (default)
  --no-images    Package files only (smaller archive)
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --with-images)
      WITH_IMAGES=1
      ;;
    --no-images)
      WITH_IMAGES=0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
  shift
done

mkdir -p "$DIST_DIR"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

cp -R "$ROOT_DIR/deploy/local/." "$OUT_DIR/"

# Exclude runtime state (models, keys, generated project files) from distributable bundle.
rm -rf "$OUT_DIR/data"
mkdir -p "$OUT_DIR/data"
cat > "$OUT_DIR/data/.gitignore" <<'EOF'
# Runtime state generated by ./start.sh
*
!.gitignore
EOF

cat > "$OUT_DIR/VERSION" <<EOF
package_name: ${PKG_NAME}
generated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
with_images: ${WITH_IMAGES}
EOF

if [ "$WITH_IMAGES" -eq 1 ]; then
  if ! command -v docker >/dev/null 2>&1; then
    echo "docker command is required for --with-images."
    exit 1
  fi

  echo "Building novelist-local image..."
  docker build -t novelist-local:latest "$ROOT_DIR"

  echo "Pulling runtime images..."
  docker pull ollama/ollama:latest
  docker pull nginx:alpine

  echo "Exporting images to images.tar..."
  docker save \
    novelist-local:latest \
    ollama/ollama:latest \
    nginx:alpine \
    -o "$OUT_DIR/images.tar"
fi

ARCHIVE_PATH="$DIST_DIR/${PKG_NAME}.tar.gz"
tar -czf "$ARCHIVE_PATH" -C "$DIST_DIR" "$PKG_NAME"

echo "Local distribution package created:"
echo "  directory: $OUT_DIR"
echo "  archive:   $ARCHIVE_PATH"
